/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektUdbudRouteImport } from './routes/projekt.udbud'
import { Route as ProjektTeknikRouteImport } from './routes/projekt.teknik'
import { Route as ProjektStartRouteImport } from './routes/projekt.start'
import { Route as ProjektDatacheckRouteImport } from './routes/projekt.datacheck'
import { Route as ProjektAdresseRouteImport } from './routes/projekt.adresse'
import { Route as ApiMapTilesRouteImport } from './routes/api.map-tiles'
import { Route as ProjektIdCockpitRouteImport } from './routes/projekt.$id.cockpit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektUdbudRoute = ProjektUdbudRouteImport.update({
  id: '/projekt/udbud',
  path: '/projekt/udbud',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektTeknikRoute = ProjektTeknikRouteImport.update({
  id: '/projekt/teknik',
  path: '/projekt/teknik',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektStartRoute = ProjektStartRouteImport.update({
  id: '/projekt/start',
  path: '/projekt/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektDatacheckRoute = ProjektDatacheckRouteImport.update({
  id: '/projekt/datacheck',
  path: '/projekt/datacheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektAdresseRoute = ProjektAdresseRouteImport.update({
  id: '/projekt/adresse',
  path: '/projekt/adresse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapTilesRoute = ApiMapTilesRouteImport.update({
  id: '/api/map-tiles',
  path: '/api/map-tiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektIdCockpitRoute = ProjektIdCockpitRouteImport.update({
  id: '/projekt/$id/cockpit',
  path: '/projekt/$id/cockpit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/map-tiles': typeof ApiMapTilesRoute
  '/projekt/adresse': typeof ProjektAdresseRoute
  '/projekt/datacheck': typeof ProjektDatacheckRoute
  '/projekt/start': typeof ProjektStartRoute
  '/projekt/teknik': typeof ProjektTeknikRoute
  '/projekt/udbud': typeof ProjektUdbudRoute
  '/projekt/$id/cockpit': typeof ProjektIdCockpitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/map-tiles': typeof ApiMapTilesRoute
  '/projekt/adresse': typeof ProjektAdresseRoute
  '/projekt/datacheck': typeof ProjektDatacheckRoute
  '/projekt/start': typeof ProjektStartRoute
  '/projekt/teknik': typeof ProjektTeknikRoute
  '/projekt/udbud': typeof ProjektUdbudRoute
  '/projekt/$id/cockpit': typeof ProjektIdCockpitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/map-tiles': typeof ApiMapTilesRoute
  '/projekt/adresse': typeof ProjektAdresseRoute
  '/projekt/datacheck': typeof ProjektDatacheckRoute
  '/projekt/start': typeof ProjektStartRoute
  '/projekt/teknik': typeof ProjektTeknikRoute
  '/projekt/udbud': typeof ProjektUdbudRoute
  '/projekt/$id/cockpit': typeof ProjektIdCockpitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/map-tiles'
    | '/projekt/adresse'
    | '/projekt/datacheck'
    | '/projekt/start'
    | '/projekt/teknik'
    | '/projekt/udbud'
    | '/projekt/$id/cockpit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/map-tiles'
    | '/projekt/adresse'
    | '/projekt/datacheck'
    | '/projekt/start'
    | '/projekt/teknik'
    | '/projekt/udbud'
    | '/projekt/$id/cockpit'
  id:
    | '__root__'
    | '/'
    | '/api/map-tiles'
    | '/projekt/adresse'
    | '/projekt/datacheck'
    | '/projekt/start'
    | '/projekt/teknik'
    | '/projekt/udbud'
    | '/projekt/$id/cockpit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMapTilesRoute: typeof ApiMapTilesRoute
  ProjektAdresseRoute: typeof ProjektAdresseRoute
  ProjektDatacheckRoute: typeof ProjektDatacheckRoute
  ProjektStartRoute: typeof ProjektStartRoute
  ProjektTeknikRoute: typeof ProjektTeknikRoute
  ProjektUdbudRoute: typeof ProjektUdbudRoute
  ProjektIdCockpitRoute: typeof ProjektIdCockpitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/udbud': {
      id: '/projekt/udbud'
      path: '/projekt/udbud'
      fullPath: '/projekt/udbud'
      preLoaderRoute: typeof ProjektUdbudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/teknik': {
      id: '/projekt/teknik'
      path: '/projekt/teknik'
      fullPath: '/projekt/teknik'
      preLoaderRoute: typeof ProjektTeknikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/start': {
      id: '/projekt/start'
      path: '/projekt/start'
      fullPath: '/projekt/start'
      preLoaderRoute: typeof ProjektStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/datacheck': {
      id: '/projekt/datacheck'
      path: '/projekt/datacheck'
      fullPath: '/projekt/datacheck'
      preLoaderRoute: typeof ProjektDatacheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/adresse': {
      id: '/projekt/adresse'
      path: '/projekt/adresse'
      fullPath: '/projekt/adresse'
      preLoaderRoute: typeof ProjektAdresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map-tiles': {
      id: '/api/map-tiles'
      path: '/api/map-tiles'
      fullPath: '/api/map-tiles'
      preLoaderRoute: typeof ApiMapTilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/$id/cockpit': {
      id: '/projekt/$id/cockpit'
      path: '/projekt/$id/cockpit'
      fullPath: '/projekt/$id/cockpit'
      preLoaderRoute: typeof ProjektIdCockpitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMapTilesRoute: ApiMapTilesRoute,
  ProjektAdresseRoute: ProjektAdresseRoute,
  ProjektDatacheckRoute: ProjektDatacheckRoute,
  ProjektStartRoute: ProjektStartRoute,
  ProjektTeknikRoute: ProjektTeknikRoute,
  ProjektUdbudRoute: ProjektUdbudRoute,
  ProjektIdCockpitRoute: ProjektIdCockpitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
