/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjektUdbudRouteImport } from './routes/projekt.udbud'
import { Route as ProjektMatchRouteImport } from './routes/projekt.match'
import { Route as ProjektHusDnaRouteImport } from './routes/projekt.hus-dna'
import { Route as ProjektFinansRouteImport } from './routes/projekt.finans'
import { Route as ProjektEngineeringRouteImport } from './routes/projekt.engineering'
import { Route as ProjektComplianceRouteImport } from './routes/projekt.compliance'
import { Route as ProjektBriefRouteImport } from './routes/projekt.brief'
import { Route as ProjektBeskrivelseRouteImport } from './routes/projekt.beskrivelse'
import { Route as ProjektAdresseRouteImport } from './routes/projekt.adresse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektUdbudRoute = ProjektUdbudRouteImport.update({
  id: '/projekt/udbud',
  path: '/projekt/udbud',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektMatchRoute = ProjektMatchRouteImport.update({
  id: '/projekt/match',
  path: '/projekt/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektHusDnaRoute = ProjektHusDnaRouteImport.update({
  id: '/projekt/hus-dna',
  path: '/projekt/hus-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektFinansRoute = ProjektFinansRouteImport.update({
  id: '/projekt/finans',
  path: '/projekt/finans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektEngineeringRoute = ProjektEngineeringRouteImport.update({
  id: '/projekt/engineering',
  path: '/projekt/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektComplianceRoute = ProjektComplianceRouteImport.update({
  id: '/projekt/compliance',
  path: '/projekt/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektBriefRoute = ProjektBriefRouteImport.update({
  id: '/projekt/brief',
  path: '/projekt/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektBeskrivelseRoute = ProjektBeskrivelseRouteImport.update({
  id: '/projekt/beskrivelse',
  path: '/projekt/beskrivelse',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektAdresseRoute = ProjektAdresseRouteImport.update({
  id: '/projekt/adresse',
  path: '/projekt/adresse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projekt/adresse': typeof ProjektAdresseRoute
  '/projekt/beskrivelse': typeof ProjektBeskrivelseRoute
  '/projekt/brief': typeof ProjektBriefRoute
  '/projekt/compliance': typeof ProjektComplianceRoute
  '/projekt/engineering': typeof ProjektEngineeringRoute
  '/projekt/finans': typeof ProjektFinansRoute
  '/projekt/hus-dna': typeof ProjektHusDnaRoute
  '/projekt/match': typeof ProjektMatchRoute
  '/projekt/udbud': typeof ProjektUdbudRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projekt/adresse': typeof ProjektAdresseRoute
  '/projekt/beskrivelse': typeof ProjektBeskrivelseRoute
  '/projekt/brief': typeof ProjektBriefRoute
  '/projekt/compliance': typeof ProjektComplianceRoute
  '/projekt/engineering': typeof ProjektEngineeringRoute
  '/projekt/finans': typeof ProjektFinansRoute
  '/projekt/hus-dna': typeof ProjektHusDnaRoute
  '/projekt/match': typeof ProjektMatchRoute
  '/projekt/udbud': typeof ProjektUdbudRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projekt/adresse': typeof ProjektAdresseRoute
  '/projekt/beskrivelse': typeof ProjektBeskrivelseRoute
  '/projekt/brief': typeof ProjektBriefRoute
  '/projekt/compliance': typeof ProjektComplianceRoute
  '/projekt/engineering': typeof ProjektEngineeringRoute
  '/projekt/finans': typeof ProjektFinansRoute
  '/projekt/hus-dna': typeof ProjektHusDnaRoute
  '/projekt/match': typeof ProjektMatchRoute
  '/projekt/udbud': typeof ProjektUdbudRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projekt/adresse'
    | '/projekt/beskrivelse'
    | '/projekt/brief'
    | '/projekt/compliance'
    | '/projekt/engineering'
    | '/projekt/finans'
    | '/projekt/hus-dna'
    | '/projekt/match'
    | '/projekt/udbud'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projekt/adresse'
    | '/projekt/beskrivelse'
    | '/projekt/brief'
    | '/projekt/compliance'
    | '/projekt/engineering'
    | '/projekt/finans'
    | '/projekt/hus-dna'
    | '/projekt/match'
    | '/projekt/udbud'
  id:
    | '__root__'
    | '/'
    | '/projekt/adresse'
    | '/projekt/beskrivelse'
    | '/projekt/brief'
    | '/projekt/compliance'
    | '/projekt/engineering'
    | '/projekt/finans'
    | '/projekt/hus-dna'
    | '/projekt/match'
    | '/projekt/udbud'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjektAdresseRoute: typeof ProjektAdresseRoute
  ProjektBeskrivelseRoute: typeof ProjektBeskrivelseRoute
  ProjektBriefRoute: typeof ProjektBriefRoute
  ProjektComplianceRoute: typeof ProjektComplianceRoute
  ProjektEngineeringRoute: typeof ProjektEngineeringRoute
  ProjektFinansRoute: typeof ProjektFinansRoute
  ProjektHusDnaRoute: typeof ProjektHusDnaRoute
  ProjektMatchRoute: typeof ProjektMatchRoute
  ProjektUdbudRoute: typeof ProjektUdbudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/udbud': {
      id: '/projekt/udbud'
      path: '/projekt/udbud'
      fullPath: '/projekt/udbud'
      preLoaderRoute: typeof ProjektUdbudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/match': {
      id: '/projekt/match'
      path: '/projekt/match'
      fullPath: '/projekt/match'
      preLoaderRoute: typeof ProjektMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/hus-dna': {
      id: '/projekt/hus-dna'
      path: '/projekt/hus-dna'
      fullPath: '/projekt/hus-dna'
      preLoaderRoute: typeof ProjektHusDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/finans': {
      id: '/projekt/finans'
      path: '/projekt/finans'
      fullPath: '/projekt/finans'
      preLoaderRoute: typeof ProjektFinansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/engineering': {
      id: '/projekt/engineering'
      path: '/projekt/engineering'
      fullPath: '/projekt/engineering'
      preLoaderRoute: typeof ProjektEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/compliance': {
      id: '/projekt/compliance'
      path: '/projekt/compliance'
      fullPath: '/projekt/compliance'
      preLoaderRoute: typeof ProjektComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/brief': {
      id: '/projekt/brief'
      path: '/projekt/brief'
      fullPath: '/projekt/brief'
      preLoaderRoute: typeof ProjektBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/beskrivelse': {
      id: '/projekt/beskrivelse'
      path: '/projekt/beskrivelse'
      fullPath: '/projekt/beskrivelse'
      preLoaderRoute: typeof ProjektBeskrivelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt/adresse': {
      id: '/projekt/adresse'
      path: '/projekt/adresse'
      fullPath: '/projekt/adresse'
      preLoaderRoute: typeof ProjektAdresseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjektAdresseRoute: ProjektAdresseRoute,
  ProjektBeskrivelseRoute: ProjektBeskrivelseRoute,
  ProjektBriefRoute: ProjektBriefRoute,
  ProjektComplianceRoute: ProjektComplianceRoute,
  ProjektEngineeringRoute: ProjektEngineeringRoute,
  ProjektFinansRoute: ProjektFinansRoute,
  ProjektHusDnaRoute: ProjektHusDnaRoute,
  ProjektMatchRoute: ProjektMatchRoute,
  ProjektUdbudRoute: ProjektUdbudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
